# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkbox_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget, key, settings):
        self.key = key
        self.settings = settings
        widget.setObjectName("widget")
        widget.resize(600, 45)
        widget.setStyleSheet("#widget {\n"
                             "    background: black;\n"
                             "    border-bottom: 1px solid #CCC\n"
                             "}\n"
                             "\n"
                             "* {\n"
                             "    color: white\n"
                             "}")
        self.label_title = QtWidgets.QLabel(widget)
        self.label_title.setGeometry(QtCore.QRect(20, 10, 471, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("")
        self.label_title.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_title.setObjectName("label_title")
        self.checkbox = QtWidgets.QWidget(widget)
        self.checkbox.setEnabled(True)
        self.checkbox.setGeometry(QtCore.QRect(555, 7, 30, 30))
        self.checkbox.setStyleSheet("#checkbox {\n"
                                    "    background: #252525; color: white\n"
                                    "}\n"
                                    "\n"
                                    "#checkbox::hover {\n"
                                    "    background: #303030;\n"
                                    "}")
        self.checkbox.setObjectName("checkbox")
        self.checkbox.mouseReleaseEvent = self.onCheckboxClicked
        self.label_checkbox = QtWidgets.QLabel(self.checkbox)
        self.label_checkbox.setGeometry(QtCore.QRect(3, 3, 24, 24))
        self.label_checkbox.setText("")
        self.label_checkbox.setPixmap(QtGui.QPixmap(":/images/check.svg"))
        self.label_checkbox.setScaledContents(True)
        self.label_checkbox.setObjectName("label_checkbox")
        self.label_checkbox.setVisible(self.settings.value(key, "true") == "true")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label_title.setText(_translate("widget", "Title text"))

    def onCheckboxClicked(self, event):
        state = not self.label_checkbox.isVisible()
        self.label_checkbox.setVisible(state)
        self.settings.setValue(self.key, state)
        self.onValueChange(state)

    def onValueChange(self, value):
        return
