# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'device.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(600, 45)
        widget.setStyleSheet("#widget {\n"
                             "    background: black;\n"
                             "    border-bottom: 1px solid #CCC\n"
                             "}\n"
                             "\n"
                             "* {\n"
                             "    color: white\n"
                             "}")
        self.label_sound = QtWidgets.QLabel(widget)
        self.label_sound.setGeometry(QtCore.QRect(10, 10, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Avenir Next LT Pro")
        font.setPointSize(14)
        self.label_sound.setFont(font)
        self.label_sound.setStyleSheet("color: #CCC")
        self.label_sound.setText("")
        self.label_sound.setPixmap(QtGui.QPixmap(":/images/sound_gray.svg"))
        self.label_sound.setScaledContents(True)
        self.label_sound.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sound.setObjectName("label_sound")
        self.label_name = QtWidgets.QLabel(widget)
        self.label_name.setGeometry(QtCore.QRect(70, 10, 300, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("")
        self.label_name.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.btn_remove = QtWidgets.QWidget(widget)
        self.btn_remove.setEnabled(True)
        self.btn_remove.setGeometry(QtCore.QRect(555, 7, 30, 30))
        self.btn_remove.setStyleSheet("#btn_remove {\n"
                                      "    background: #252525; color: white\n"
                                      "}\n"
                                      "\n"
                                      "#btn_remove::hover {\n"
                                      "    background: #303030;\n"
                                      "}\n"
                                      "\n"
                                      "#btn_remove::!enabled {\n"
                                      "    background: #595959;\n"
                                      "    border-bottom: 3px solid #E00000;\n"
                                      "}")
        self.btn_remove.setObjectName("btn_remove")
        self.label_btn_remove = QtWidgets.QLabel(self.btn_remove)
        self.label_btn_remove.setGeometry(QtCore.QRect(3, 3, 24, 24))
        self.label_btn_remove.setText("")
        self.label_btn_remove.setPixmap(QtGui.QPixmap(":/images/remove.svg"))
        self.label_btn_remove.setScaledContents(True)
        self.label_btn_remove.setObjectName("label_btn_remove")
        self.btn_disconnect = QtWidgets.QWidget(widget)
        self.btn_disconnect.setEnabled(True)
        self.btn_disconnect.setGeometry(QtCore.QRect(515, 7, 30, 30))
        self.btn_disconnect.setStyleSheet("#btn_disconnect {\n"
                                          "    background: #252525; color: white\n"
                                          "}\n"
                                          "\n"
                                          "#btn_disconnect::hover {\n"
                                          "    background: #303030;\n"
                                          "}\n"
                                          "\n"
                                          "#btn_disconnect::!enabled {\n"
                                          "    background: #595959;\n"
                                          "    border-bottom: 3px solid #E00000;\n"
                                          "}")
        self.btn_disconnect.setObjectName("btn_disconnect")
        self.label_btn_disconnect = QtWidgets.QLabel(self.btn_disconnect)
        self.label_btn_disconnect.setGeometry(QtCore.QRect(3, 3, 24, 24))
        self.label_btn_disconnect.setText("")
        self.label_btn_disconnect.setPixmap(QtGui.QPixmap(":/images/disconnect.svg"))
        self.label_btn_disconnect.setScaledContents(True)
        self.label_btn_disconnect.setObjectName("label_btn_disconnect")
        self.btn_sound = QtWidgets.QWidget(widget)
        self.btn_sound.setEnabled(True)
        self.btn_sound.setGeometry(QtCore.QRect(475, 7, 30, 30))
        self.btn_sound.setStyleSheet("#btn_sound {\n"
                                     "    background: #252525; color: white\n"
                                     "}\n"
                                     "\n"
                                     "#btn_sound::hover {\n"
                                     "    background: #303030;\n"
                                     "}\n"
                                     "\n"
                                     "#btn_sound::!enabled {\n"
                                     "    background: #595959;\n"
                                     "    border-bottom: 3px solid #E00000;\n"
                                     "}")
        self.btn_sound.setObjectName("btn_sound")
        self.label_btn_sound = QtWidgets.QLabel(self.btn_sound)
        self.label_btn_sound.setGeometry(QtCore.QRect(3, 3, 24, 24))
        self.label_btn_sound.setText("")
        self.label_btn_sound.setPixmap(QtGui.QPixmap(":/images/sound_white.svg"))
        self.label_btn_sound.setScaledContents(True)
        self.label_btn_sound.setObjectName("label_btn_sound")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label_name.setText(_translate("widget", "Device"))
