# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'folder.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
import ui.media_file_browser as media_file_browser


class Ui_widget(object):
    def setupUi(self, widget, owner):
        self.owner = owner
        widget.setObjectName("widget")
        widget.resize(600, 35)
        widget.setStyleSheet("#widget {\n"
                             "    background: black;\n"
                             "    border-bottom: 1px solid #CCC\n"
                             "}\n"
                             "\n"
                             "* {\n"
                             "    color: white\n"
                             "}")
        self.label_folder = QtWidgets.QLabel(widget)
        self.label_folder.setGeometry(QtCore.QRect(10, 5, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat Light")
        font.setPointSize(13)
        self.label_folder.setFont(font)
        self.label_folder.setStyleSheet("color: #CCC")
        self.label_folder.setText("")
        self.label_folder.setPixmap(QtGui.QPixmap(":/images/folder.svg"))
        self.label_folder.setScaledContents(True)
        self.label_folder.setAlignment(QtCore.Qt.AlignCenter)
        self.label_folder.setObjectName("label_folder")
        self.label_title = QtWidgets.QLabel(widget)
        self.label_title.setGeometry(QtCore.QRect(70, 5, 300, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat Light")
        font.setPointSize(13)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("")
        self.label_title.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_title.setObjectName("label_title")

        self.retranslateUi(widget)
        widget.mouseReleaseEvent = self.enterFolder
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label_title.setText(_translate("widget", "Title text"))

    def enterFolder(self, event):
        self.owner.changePath(os.path.join(self.owner.current_path, self.label_title.text()))
