# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'percentage_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(600, 45)
        widget.setStyleSheet("#widget {\n"
                             "    background: black;\n"
                             "    border-bottom: 1px solid #CCC\n"
                             "}\n"
                             "\n"
                             "* {\n"
                             "    color: white\n"
                             "}")
        self.label_title = QtWidgets.QLabel(widget)
        self.label_title.setGeometry(QtCore.QRect(20, 15, 391, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("")
        self.label_title.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_title.setObjectName("label_title")
        self.percentage_box = QtWidgets.QWidget(widget)
        self.percentage_box.setEnabled(True)
        self.percentage_box.setGeometry(QtCore.QRect(455, 7, 130, 30))
        self.percentage_box.setStyleSheet("#percentage_box {\n"
                                          "    background: #252525; color: white\n"
                                          "}\n"
                                          "\n"
                                          "#percentage_box::hover {\n"
                                          "    background: #303030;\n"
                                          "}")
        self.percentage_box.setObjectName("percentage_box")
        self.label_percentage = QtWidgets.QLabel(self.percentage_box)
        self.label_percentage.setGeometry(QtCore.QRect(40, 5, 50, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.label_percentage.setFont(font)
        self.label_percentage.setStyleSheet("")
        self.label_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.label_percentage.setObjectName("label_percentage")
        self.btn_decrease = QtWidgets.QLabel(self.percentage_box)
        self.btn_decrease.setGeometry(QtCore.QRect(5, 3, 24, 24))
        self.btn_decrease.setText("")
        self.btn_decrease.setPixmap(QtGui.QPixmap(":/images/minus.svg"))
        self.btn_decrease.setScaledContents(True)
        self.btn_decrease.setObjectName("btn_decrease")
        self.btn_increase = QtWidgets.QLabel(self.percentage_box)
        self.btn_increase.setGeometry(QtCore.QRect(101, 3, 24, 24))
        self.btn_increase.setText("")
        self.btn_increase.setPixmap(QtGui.QPixmap(":/images/plus.svg"))
        self.btn_increase.setScaledContents(True)
        self.btn_increase.setObjectName("btn_increase")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label_title.setText(_translate("widget", "Title text"))
        self.label_percentage.setText(_translate("widget", "80 %"))
