# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'android_auto.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_content(object):
    def setupUi(self, content, owner):
        self.owner = owner
        content.setObjectName("content")
        content.resize(720, 435)
        content.setStyleSheet("#content {\n"
                              "    background: black;\n"
                              "}\n"
                              "\n"
                              "* {\n"
                              "    color: white;\n"
                              "}")
        self.label_howto = QtWidgets.QLabel(content)
        self.label_howto.setGeometry(QtCore.QRect(60, 120, 600, 100))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.label_howto.setFont(font)
        self.label_howto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_howto.setObjectName("label_howto")

        self.retranslateUi(content)
        QtCore.QMetaObject.connectSlotsByName(content)

    def retranslateUi(self, content):
        _translate = QtCore.QCoreApplication.translate
        content.setWindowTitle(_translate("content", "Form"))
        self.label_howto.setText(_translate("content", "1. Connect your Android mobile phone via USB\n"
                                                       "\n"
                                                       "2. Go back to the home screen and reopen Android Auto"))
