# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'android_auto.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_content(object):
    def setupUi(self, content, owner):
        self.owner = owner
        content.setObjectName("content")
        content.resize(720, 435)
        content.setStyleSheet("#content {\n"
                              "    background: black;\n"
                              "}\n"
                              "\n"
                              "* {\n"
                              "    color: white;\n"
                              "}")
        self.label_howto = QtWidgets.QLabel(content)
        self.label_howto.setGeometry(QtCore.QRect(60, 120, 600, 100))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.label_howto.setFont(font)
        self.label_howto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_howto.setObjectName("label_howto")
        self.btn_launch = QtWidgets.QWidget(content)
        self.btn_launch.setEnabled(True)
        self.btn_launch.setGeometry(QtCore.QRect(300, 260, 120, 35))
        self.btn_launch.setStyleSheet("#btn_launch {\n"
                                      "    background: #252525; color: white\n"
                                      "}\n"
                                      "\n"
                                      "#btn_launch::hover {\n"
                                      "    background: #303030;\n"
                                      "}\n"
                                      "\n"
                                      "#btn_launch::!enabled {\n"
                                      "    background: #595959;\n"
                                      "    border-bottom: 3px solid #E00000;\n"
                                      "}")
        self.btn_launch.setObjectName("btn_launch")
        self.btn_launch.mouseReleaseEvent = self.bindAndroidAuto
        self.text_btn_launch = QtWidgets.QLabel(self.btn_launch)
        self.text_btn_launch.setGeometry(QtCore.QRect(10, 5, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.text_btn_launch.setFont(font)
        self.text_btn_launch.setLineWidth(1)
        self.text_btn_launch.setAlignment(QtCore.Qt.AlignCenter)
        self.text_btn_launch.setObjectName("text_btn_launch")

        self.retranslateUi(content)
        QtCore.QMetaObject.connectSlotsByName(content)

    def retranslateUi(self, content):
        _translate = QtCore.QCoreApplication.translate
        content.setWindowTitle(_translate("content", "Form"))
        self.label_howto.setText(_translate("content", "1. Connect your Android mobile phone via USB\n"
                                                       "\n"
                                                       "2. Click on \"Launch\" to launch Android Auto"))
        self.text_btn_launch.setText(_translate("content", "Launch"))

    def bindAndroidAuto(self, event):
        self.owner.switchToAndroidAuto()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    content = QtWidgets.QWidget()
    ui = Ui_content()
    ui.setupUi(content)
    content.show()
    sys.exit(app.exec_())
