# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cockpit.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

import obd
from PIL.ImageQt import ImageQt
from PyQt5 import QtCore, QtGui, QtWidgets
from PIL import Image


class Ui_content(object):
    def setupUi(self, content, obd_conn):
        content.setObjectName("content")
        content.resize(660, 300)
        content.setStyleSheet("#content {\n"
                              "    background: black\n"
                              "}\n"
                              "\n"
                              "* {\n"
                              "    color: white\n"
                              "}")
        self.rotation_gauge = QtWidgets.QLabel(content)
        self.rotation_gauge.setGeometry(QtCore.QRect(30, 60, 260, 195))
        self.rotation_gauge.setText("")
        self.rotation_gauge.setPixmap(QtGui.QPixmap(":/images/rotation_gauge.png"))
        self.rotation_gauge.setScaledContents(True)
        self.rotation_gauge.setObjectName("rotation_gauge")
        self.speed_gauge = QtWidgets.QLabel(content)
        self.speed_gauge.setGeometry(QtCore.QRect(370, 60, 260, 195))
        self.speed_gauge.setText("")
        self.speed_gauge.setPixmap(QtGui.QPixmap(":/images/speed_gauge.png"))
        self.speed_gauge.setScaledContents(True)
        self.speed_gauge.setObjectName("speed_gauge")
        self.label_gear = QtWidgets.QLabel(content)
        self.label_gear.setGeometry(QtCore.QRect(230, 30, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.label_gear.setFont(font)
        self.label_gear.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gear.setObjectName("label_gear")
        self.label_rpm = QtWidgets.QLabel(content)
        self.label_rpm.setGeometry(QtCore.QRect(110, 100, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        self.label_rpm.setStyleSheet("color: #999")
        self.label_rpm.setFont(font)
        self.label_rpm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rpm.setObjectName("label_rpm")
        self.label_kmph = QtWidgets.QLabel(content)
        self.label_kmph.setGeometry(QtCore.QRect(450, 100, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        self.label_kmph.setStyleSheet("color: #999")
        self.label_kmph.setFont(font)
        self.label_kmph.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kmph.setObjectName("label_kmph")
        self.label_speed = QtWidgets.QLabel(content)
        self.label_speed.setGeometry(QtCore.QRect(450, 250, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.label_speed.setFont(font)
        self.label_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_speed.setObjectName("label_speed")
        self.label_rotation = QtWidgets.QLabel(content)
        self.label_rotation.setGeometry(QtCore.QRect(110, 250, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.label_rotation.setFont(font)
        self.label_rotation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rotation.setObjectName("label_rotation")


        self.speed = 0
        self.rpm = 0

        obd_conn.watch(obd.commands.RPM, callback=self.rpmChanged)
        obd_conn.watch(obd.commands.SPEED, callback=self.speedChanged)

        self.retranslateUi(content)
        QtCore.QMetaObject.connectSlotsByName(content)

        self.initUI()

    def retranslateUi(self, content):
        _translate = QtCore.QCoreApplication.translate
        content.setWindowTitle(_translate("content", "Form"))
        self.label_gear.setText(_translate("content", "No\nConnection"))
        self.label_speed.setText(_translate("content", "0 km/h"))
        self.label_rotation.setText(_translate("content", "0 rpm"))
        self.label_rpm.setText(_translate("content", "rpm"))
        self.label_kmph.setText(_translate("content", "km/h"))

    def rpmChanged(self, r):
        if not r.is_null():
            self.rpm = float(str(r).split(" ")[0])
            print("RPM: " + str(self.rpm))
            percent = self.rpm / 7000
            rotation = 120 - 240 * percent
            scriptDir = os.path.dirname(__file__)
            dial = Image.open(os.path.join(scriptDir, "res/needle.png")).convert("RGBA")
            dial = dial.rotate(rotation, resample=Image.BICUBIC, center=(200, 185))

            gauge = Image.open(os.path.join(scriptDir, "res/rotation_gauge.png"))
            gauge.paste(dial, mask=dial)
            qt_gauge = ImageQt(gauge)
            pixmap = QtGui.QPixmap.fromImage(qt_gauge)
            self.rotation_gauge.setPixmap(pixmap)
            self.label_rotation.setText(str(int(self.rpm)) + " rpm")

    def speedChanged(self, s):
        self.label_gear.setText("")
        if not s.is_null():
            self.speed = float(str(s).split(" ")[0])
            print("RPM: " + str(self.speed))
            percent = self.speed / 220
            rotation = 120 - 240 * percent
            scriptDir = os.path.dirname(__file__)
            dial = Image.open(os.path.join(scriptDir, "res/needle.png")).convert("RGBA")
            dial = dial.rotate(rotation, resample=Image.BICUBIC, center=(200, 185))

            gauge = Image.open(os.path.join(scriptDir, "res/speed_gauge.png"))
            gauge.paste(dial, mask=dial)

            qt_gauge = ImageQt(gauge)
            pixmap = QtGui.QPixmap.fromImage(qt_gauge)
            self.speed_gauge.setPixmap(pixmap)
            self.label_speed.setText(str(self.speed) + " km/h")

    def initUI(self):
        # Speed
        percent = 0
        rotation = 120 - 240 * percent
        scriptDir = os.path.dirname(__file__)
        dial = Image.open(os.path.join(scriptDir, "res/needle.png")).convert("RGBA")
        dial = dial.rotate(rotation, resample=Image.BICUBIC, center=(200, 185))

        gauge = Image.open(os.path.join(scriptDir, "res/speed_gauge.png"))
        gauge.paste(dial, mask=dial)

        qt_gauge = ImageQt(gauge)
        pixmap = QtGui.QPixmap.fromImage(qt_gauge)
        self.speed_gauge.setPixmap(pixmap)

        # RPM
        percent = 0
        rotation = 120 - 240 * percent
        dial = Image.open(os.path.join(scriptDir, "res/needle.png")).convert("RGBA")
        dial = dial.rotate(rotation, resample=Image.BICUBIC, center=(200, 185))

        gauge = Image.open(os.path.join(scriptDir, "res/rotation_gauge.png"))
        gauge.paste(dial, mask=dial)
        qt_gauge = ImageQt(gauge)
        pixmap = QtGui.QPixmap.fromImage(qt_gauge)
        self.rotation_gauge.setPixmap(pixmap)
