# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cockpit.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PIL.ImageQt import ImageQt
from PyQt5 import QtCore, QtGui, QtWidgets
from PIL import Image


class Ui_content(object):
    def setupUi(self, content):
        content.setObjectName("content")
        content.resize(660, 300)
        content.setStyleSheet("#content {\n"
                              "    background: black\n"
                              "}\n"
                              "\n"
                              "* {\n"
                              "    color: white\n"
                              "}")
        self.rotation_gauge = QtWidgets.QLabel(content)
        self.rotation_gauge.setGeometry(QtCore.QRect(30, 60, 260, 195))
        self.rotation_gauge.setText("")
        self.rotation_gauge.setPixmap(QtGui.QPixmap(":/images/rotation_gauge.png"))
        self.rotation_gauge.setScaledContents(True)
        self.rotation_gauge.setObjectName("rotation_gauge")
        self.speed_gauge = QtWidgets.QLabel(content)
        self.speed_gauge.setGeometry(QtCore.QRect(370, 60, 260, 195))
        self.speed_gauge.setText("")
        self.speed_gauge.setPixmap(QtGui.QPixmap(":/images/speed_gauge.png"))
        self.speed_gauge.setScaledContents(True)
        self.speed_gauge.setObjectName("speed_gauge")
        self.label_gear = QtWidgets.QLabel(content)
        self.label_gear.setGeometry(QtCore.QRect(280, 30, 100, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.label_gear.setFont(font)
        self.label_gear.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gear.setObjectName("label_gear")

        self.retranslateUi(content)
        QtCore.QMetaObject.connectSlotsByName(content)

        self.updateUi()

    def retranslateUi(self, content):
        _translate = QtCore.QCoreApplication.translate
        content.setWindowTitle(_translate("content", "Form"))
        self.label_gear.setText(_translate("content", "Gear 3"))

    def updateUi(self):
        # Speed
        speed = 102
        percent = speed / 220
        rotation = 120 - 240 * percent
        scriptDir = os.path.dirname(__file__)
        dial = Image.open(os.path.join(scriptDir, "res/needle.png")).convert("RGBA")
        dial = dial.rotate(rotation, resample=Image.BICUBIC, center=(200, 185))

        gauge = Image.open(os.path.join(scriptDir, "res/speed_gauge.png"))
        gauge.paste(dial, mask=dial)

        qt_gauge = ImageQt(gauge)
        pixmap = QtGui.QPixmap.fromImage(qt_gauge)
        self.speed_gauge.setPixmap(pixmap)

        # RPM
        rpm = 1600
        percent = rpm / 7000
        rotation = 120 - 240 * percent
        dial = Image.open(os.path.join(scriptDir, "res/needle.png")).convert("RGBA")
        dial = dial.rotate(rotation, resample=Image.BICUBIC, center=(200, 185))

        gauge = Image.open(os.path.join(scriptDir, "res/rotation_gauge.png"))
        gauge.paste(dial, mask=dial)
        qt_gauge = ImageQt(gauge)
        pixmap = QtGui.QPixmap.fromImage(qt_gauge)
        self.rotation_gauge.setPixmap(pixmap)
