# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ui.lists.checkbox_setting
import ui.lists.number_setting
import ui.lists.favourite_setting
import screen_brightness_control as screen


class Ui_content(object):
    def setupUi(self, content):
        content.setObjectName("content")
        content.resize(720, 435)
        content.setStyleSheet("#content {\n"
                              "    background: black;\n"
                              "}\n"
                              "\n"
                              "* {\n"
                              "    color: white;\n"
                              "}")
        self.btn_display = QtWidgets.QWidget(content)
        self.btn_display.setEnabled(False)
        self.btn_display.setGeometry(QtCore.QRect(30, 30, 180, 45))
        self.btn_display.setStyleSheet("#btn_display {\n"
                                       "    background: #252525; color: white\n"
                                       "}\n"
                                       "\n"
                                       "#btn_display::hover {\n"
                                       "    background: #303030;\n"
                                       "}\n"
                                       "\n"
                                       "#btn_display::!enabled {\n"
                                       "    background: #595959;\n"
                                       "    border-bottom: 3px solid #E00000;\n"
                                       "}")
        self.btn_display.setObjectName("btn_display")
        self.btn_display.mouseReleaseEvent = self.switchToDisplay
        self.text_btn_display = QtWidgets.QLabel(self.btn_display)
        self.text_btn_display.setGeometry(QtCore.QRect(20, 10, 140, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.text_btn_display.setFont(font)
        self.text_btn_display.setLineWidth(1)
        self.text_btn_display.setAlignment(QtCore.Qt.AlignCenter)
        self.text_btn_display.setObjectName("text_btn_display")
        self.btn_sound = QtWidgets.QWidget(content)
        self.btn_sound.setEnabled(True)
        self.btn_sound.setGeometry(QtCore.QRect(230, 30, 180, 45))
        self.btn_sound.setStyleSheet("#btn_sound {\n"
                                     "    background: #252525; color: white\n"
                                     "}\n"
                                     "\n"
                                     "#btn_sound::hover {\n"
                                     "    background: #303030;\n"
                                     "}\n"
                                     "\n"
                                     "#btn_sound::!enabled {\n"
                                     "    background: #595959;\n"
                                     "    border-bottom: 3px solid #E00000;\n"
                                     "}")
        self.btn_sound.setObjectName("btn_sound")
        self.btn_sound.mouseReleaseEvent = self.switchToSound
        self.text_btn_sound = QtWidgets.QLabel(self.btn_sound)
        self.text_btn_sound.setGeometry(QtCore.QRect(20, 10, 140, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.text_btn_sound.setFont(font)
        self.text_btn_sound.setLineWidth(1)
        self.text_btn_sound.setAlignment(QtCore.Qt.AlignCenter)
        self.text_btn_sound.setObjectName("text_btn_sound")
        self.btn_radio = QtWidgets.QWidget(content)
        self.btn_radio.setEnabled(True)
        self.btn_radio.setGeometry(QtCore.QRect(430, 30, 180, 45))
        self.btn_radio.setStyleSheet("#btn_radio {\n"
                                     "    background: #252525; color: white\n"
                                     "}\n"
                                     "\n"
                                     "#btn_radio::hover {\n"
                                     "    background: #303030;\n"
                                     "}\n"
                                     "\n"
                                     "#btn_radio::!enabled {\n"
                                     "    background: #595959;\n"
                                     "    border-bottom: 3px solid #E00000;\n"
                                     "}")
        self.btn_radio.setObjectName("btn_radio")
        self.btn_radio.mouseReleaseEvent = self.switchToRadio
        self.text_btn_radio = QtWidgets.QLabel(self.btn_radio)
        self.text_btn_radio.setGeometry(QtCore.QRect(20, 10, 140, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.text_btn_radio.setFont(font)
        self.text_btn_radio.setLineWidth(1)
        self.text_btn_radio.setAlignment(QtCore.Qt.AlignCenter)
        self.text_btn_radio.setObjectName("text_btn_radio")
        self.label_version = QtWidgets.QLabel(content)
        self.label_version.setGeometry(QtCore.QRect(30, 405, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label_version.setFont(font)
        self.label_version.setObjectName("label_version")
        self.container = QtWidgets.QWidget(content)
        self.container.setGeometry(QtCore.QRect(30, 100, 660, 281))
        self.container.setObjectName("container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(content)
        QtCore.QMetaObject.connectSlotsByName(content)
        self.settings = QtCore.QSettings("Cacaonut", "Headunit")
        self.switchToDisplay(None)

    def retranslateUi(self, content):
        _translate = QtCore.QCoreApplication.translate
        content.setWindowTitle(_translate("content", "Form"))
        self.text_btn_display.setText(_translate("content", "Display"))
        self.text_btn_sound.setText(_translate("content", "Sound"))
        self.text_btn_radio.setText(_translate("content", "Radio"))
        self.label_version.setText(_translate("content", "Version 0.1.0-alpha"))

    def switchToDisplay(self, event):
        self.btn_display.setEnabled(False)
        self.btn_sound.setEnabled(True)
        self.btn_radio.setEnabled(True)

        for i in reversed(range(self.verticalLayout.count())):
            self.verticalLayout.itemAt(i).widget().setParent(None)

        content_auto_brightness = QtWidgets.QWidget()
        ui_auto_brightness = ui.lists.checkbox_setting.Ui_widget()
        ui_auto_brightness.setupUi(content_auto_brightness, "display/auto_brightness", self.settings)
        ui_auto_brightness.label_title.setText("Automatically adapt brightness")
        self.verticalLayout.addWidget(content_auto_brightness)

        content_brightness = QtWidgets.QWidget()
        ui_brightness = ui.lists.number_setting.Ui_widget()
        ui_brightness.setupUi(content_brightness, "display/brightness", self.settings, 10, 10, 100, unit="%")
        ui_brightness.onValueChange = lambda value: screen.set_brightness(value)
        ui_brightness.label_title.setText("Brightness")
        self.verticalLayout.addWidget(content_brightness)

        self.container.setFixedHeight(self.verticalLayout.count() * 45)

    def switchToSound(self, event):
        self.btn_display.setEnabled(True)
        self.btn_sound.setEnabled(False)
        self.btn_radio.setEnabled(True)

        for i in reversed(range(self.verticalLayout.count())):
            self.verticalLayout.itemAt(i).widget().setParent(None)

        content_volume = QtWidgets.QWidget()
        ui_volume = ui.lists.number_setting.Ui_widget()
        ui_volume.setupUi(content_volume, "sound/volume", self.settings, 2, 0, 100)
        ui_volume.label_title.setText("Volume")
        self.verticalLayout.addWidget(content_volume)

        content_balance_left_right = QtWidgets.QWidget()
        ui_balance_left_right = ui.lists.number_setting.Ui_widget()
        ui_balance_left_right.setupUi(content_balance_left_right, "sound/balance_left_right", self.settings, 1, -5, 5)
        ui_balance_left_right.label_title.setText("Balance left - right")
        self.verticalLayout.addWidget(content_balance_left_right)

        content_balance_front_back = QtWidgets.QWidget()
        ui_balance_front_back = ui.lists.number_setting.Ui_widget()
        ui_balance_front_back.setupUi(content_balance_front_back, "sound/balance_front_back", self.settings, 1, -5, 5)
        ui_balance_front_back.label_title.setText("Balance front - back")
        self.verticalLayout.addWidget(content_balance_front_back)

        self.container.setFixedHeight(self.verticalLayout.count() * 45)

    def switchToRadio(self, event):
        self.btn_display.setEnabled(True)
        self.btn_sound.setEnabled(True)
        self.btn_radio.setEnabled(False)

        for i in reversed(range(self.verticalLayout.count())):
            self.verticalLayout.itemAt(i).widget().setParent(None)

        content_favourite_1 = QtWidgets.QWidget()
        ui_favourite_1 = ui.lists.favourite_setting.Ui_widget()
        ui_favourite_1.setupUi(content_favourite_1, "radio/favourite_1", self.settings)
        ui_favourite_1.label_title.setText("Favourite #1")
        self.verticalLayout.addWidget(content_favourite_1)

        content_favourite_2 = QtWidgets.QWidget()
        ui_favourite_2 = ui.lists.favourite_setting.Ui_widget()
        ui_favourite_2.setupUi(content_favourite_2, "radio/favourite_2", self.settings)
        ui_favourite_2.label_title.setText("Favourite #2")
        self.verticalLayout.addWidget(content_favourite_2)

        content_favourite_3 = QtWidgets.QWidget()
        ui_favourite_3 = ui.lists.favourite_setting.Ui_widget()
        ui_favourite_3.setupUi(content_favourite_3, "radio/favourite_3", self.settings)
        ui_favourite_3.label_title.setText("Favourite #3")
        self.verticalLayout.addWidget(content_favourite_3)

        content_favourite_4 = QtWidgets.QWidget()
        ui_favourite_4 = ui.lists.favourite_setting.Ui_widget()
        ui_favourite_4.setupUi(content_favourite_4, "radio/favourite_4", self.settings)
        ui_favourite_4.label_title.setText("Favourite #4")
        self.verticalLayout.addWidget(content_favourite_4)

        content_favourite_5 = QtWidgets.QWidget()
        ui_favourite_5 = ui.lists.favourite_setting.Ui_widget()
        ui_favourite_5.setupUi(content_favourite_5, "radio/favourite_5", self.settings)
        ui_favourite_5.label_title.setText("Favourite #5")
        self.verticalLayout.addWidget(content_favourite_5)

        content_limit = QtWidgets.QWidget()
        ui_limit = ui.lists.number_setting.Ui_widget()
        ui_limit.setupUi(content_limit, "radio/limit", self.settings, 1, -40, -10, unit="dB")
        ui_limit.label_title.setText("Scan power limit")
        self.verticalLayout.addWidget(content_limit)

        self.container.setFixedHeight(self.verticalLayout.count() * 45)

